actstream/templates/actstream/action.html

Bug causes AttributeError failure when action has no target

Template bug - action object url incorrect

---

actstream/registry.py

Registry breaks if model is located somewhere other than app.models and explicitly bound to app by Meta's `app_label`. And the code just looks a little bit more clear (no need to use `re`).

Using _meta.app_label for is_installed method

---

actstream/apps.py
actstream/compat.py
actstream/compat_apps.py
actstream/runtests/testapp/apps.py
actstream/runtests/testapp_nested/apps.py
tox.ini

This seems to work. Refer to #270 to see discussion about what change in Django 1.9 caused this. 
I broke compat.py into compat.py and compat_apps.py, in order to get around the need to import get_model from multiple places, and so we can use AppConfig without running into the same issue we were trying to fix.
Let me know if I can improve this.

Fix #270: Add Django 1.9 compatibility

---

docs/source/data.rst
docs/source/installation.rst

https://github.com/bradjasper/django-jsonfield/ is a different project that's called `jsonfield` in pypi.

Docs: fix link to django-jsonfield project

---

actstream/registry.py

How would you like the unit test done for this? defer is only on 1.7+.
I could make a new field or a new model. Check if the version is > 1.7, if yes make it defer in the get_queryset function of the manager. Then just make a test that uses that field or model which would fail without this pull and pass with it.

Fixed #258 works with defer

---

actstream/migrations/0001_initial.py
actstream/models.py

Beginning in Django 2.0, the 'on_delete' argument will be required for any
ForeignKey model fields.  The default behavior in Django is to CASCADE delete
a Model when its related field is removed, so I added this definition to the
existing Model fields:
- Follow.user
- Follow.content_type
- Action.actor_content_type
- Action.target_content_type
- Action.action_object_content_type
These changes should be backwards-compatible with any existing installation.
I also added these definitions to the migrations files--though not the
south_migrations (since it's unlikely South would be used in a Django 2.0
installation at this point).
I did this mainly to get rid of the many 'RemovedInDjango20Warning'
deprecation notices in my Django 1.9 installation, but will allow the module
to be compatible with …

Added explicit 'on_delete' arg to ForeignKey fields

---

actstream/views.py

After doing some checking in the official release notes in django 1.10, I realized that the context_instance for both render_to_response and render were both deprecated. Since 
`render(request, context, template_name)`
is technically the same as 
`render_to_response(template_name,  {...}, context_instance=RequestContext(request))`
It is the best substitute in this case.

Changed the render_to_response to render since the prior was deprecated in django 1.10

---

actstream/apps.py
actstream/migrations/0001_initial.py
docs/requirements.txt
tox.ini

This commit integrates django-jsonfield-compat, which is a solution to #294.
After using this branch, add
```
USE_NATIVE_JSONFIELD = True
```
to your project's settings, and then run `python manage.py migrate`.
This will update all JSONFields to be a native JSONField type, assuming you're using PostgreSQL and Django >= 1.9. You can switch everything back by changing the above setting to `False`, just be sure to run migrate again afterwards.

Integrate jsonfield_compat

---

actstream/templatetags/activity_tags.py

Since `context` contains `'action'` at this point, please do not leave out the rest of the context as it may be necessary for custom `actstream/action.html` templates.

Send full 1.11 compatible context into templates

---

actstream/actions.py
actstream/models.py
actstream/registry.py
actstream/runtests/settings.py
actstream/views.py

Currently the builds are not working at all, these changes should at least make them run.
I managed to fix all but the `test_not_installed` before I ran out of time. That one is a bit tricky since since I'm getting
`django.core.exceptions.ImproperlyConfigured: The model <class 'testapp_nested.tests.get_test_model.<locals>.NotInstalledModel'> is abstract, so it cannot be registered with actstream.` 
which means that it finds the model twice for some reason. Hopefully someone with more time on their hands will be able to fix the remaining one issue :)

Make builds run again and fix most of the tests

---

.travis.yml
actstream/apps.py
actstream/jsonfield.py
actstream/migrations/0001_initial.py
docs/source/changelog.rst
docs/source/data.rst
tox.ini

This PR adds optional support for **django-mysql**'s [ JSONField](https://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html) (supported by MySQL **5.7**+) to be used instead of the already supported [django-jsonfield](https://github.com/dmkoch/django-jsonfield) and [Django TextField](https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.TextField) fallback.
We are using MySQL and django-mysql's JSONField already and would like to use this library without having to rely on a different JSONField implementation. See https://github.com/justquick/django-activity-stream/issues/415
The new `actstream.jsonfield` module is responsible to choose a suitable `JSONField` implementation on startup:
- `USE_JSONFIELD = True` and `django-jsonfield` + …

Add support for django-mysql's JSONField as alternative implementation

---

actstream/jsonfield.py

Removes an unnecessary print statement that is cluttering up the console on app startup.

Remove print statement from jsonfield

---

actstream/managers.py
actstream/tests/test_activity.py

Hi! 
I met a use case in which it would be useful to get a user stream associated with a particular follow `flag`. For instance to get all the actions concerning an object that a user is _watching_ but not _liking_.
Note that if a user a following an object with two different flags, and we only query for one of them, we will get back all the actions of the followed object. But this is an expected behaviour since the user is following the object anyways. Obviously, actions can't be linked backed to following flags.
This is a quite simple change. I also added a test.
I would be happy to discuss any remark!

Filter user stream by follow flag

---

actstream/models.py

```
try:
from django.utils import timezone
now = timezone.now # L18
except ImportError:
from datetime import datetime
now = datetime.now # L21
```
and  `now = timezone.now` # L27 should be removed

Remove duplicate rows（`now = timezone.now` # L18，L21 & -L27）

---

actstream/models.py

Dear all,
Could you please fix that line? The function "python_2_unicode_compatible", which was part of "django.utils.encoding", seems to have been moved to "six". https://stackoverflow.com/a/43640425
The following error is thrown when Django (3.0.0) tries to load actstream:
```
File "/usr/local/lib/python3.6/site-packages/actstream/models.py", line 7, in <module>
from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'
```
Best regards,
Ricardo Rodriguez.

Remove line importing python_2_unicode_compatible

---

.travis.yml
actstream/actions.py
actstream/feeds.py
actstream/gfk.py
actstream/models.py
actstream/registry.py
actstream/templatetags/activity_tags.py
actstream/tests/base.py
actstream/tests/test_activity.py
actstream/tests/test_views.py
actstream/tests/test_zombies.py
actstream/urls.py
actstream/views.py
runtests/testapp/urls.py
runtests/urls.py
tox.ini

Progress on #438. This should handle all `ImportError` exceptions for APIs deprecated in Django 3, excluding the ones from dependencies used for JSON field support

Remove Python 2 compatibility APIs

---

docs/source/installation.rst

The currentl link points to bitbucket where the README reads: 
> django-jsonfield
> This project is now maintained by Adam Johnson and and hosted on GitHub at https://github.com/adamchainz/django-jsonfield .
So is confirmed by the PyPI listing where the homepage link points to Adam's repository.
The proposed change links to PyPI directly which is supposed to be the source of truth for those things :)

Update link to django-jsonfield

---

setup.py

Can we consider using setuptools with an optional fallback to distutils?
I think it's possible with the current setup.py file to support both options.
It will help a lot since I have troubles installing the package directly from the master using poetry:
https://github.com/python-poetry/poetry and this patch will resolve my issue.
Thanks for the great package!

Add support of setuptools

---

actstream/apps.py
actstream/tests/test_apps.py

An app can be reloaded during tests if `INSTALLED_APPS` is modified using `override_settings` or `modify_settings`, this would cause the data field to be added to `Action._meta.fields` multiple times and this leads to an error when you try to save an action because django will generate an sql query with the data column included multiple times, this PR prevents that.

Make sure Action.data field is not added twice in ActstreamConfig

---

actstream/feeds.py
actstream/tests/base.py
actstream/tests/test_feeds.py
docs/source/feeds.rst

I liked to have a feature that I can get the user own activity by passing ``with_user_activity=True`` through query parameter like ``/activity/feed/json/with_user_activity=true``. 
So I added the ``items`` function to ``UserActivityMixin``. Take a look at the code and tell me your comments about that or this feature.

Feature of having with_user_activity=True parameter when using User Activity Feed  (User Stream) url

---

Dockerfile
docker-compose.yml
docs/source/development.rst
docs/source/index.rst
runtests/requirements.txt

To simplify local development and reduce the need to have virtualenv and other libs installed, this PR adds a simple docker container to run tests in.

Add docker env for local development

---

README.rst

Travis still shows failing but the project is built on GitHub actions now which run successfully!

Change build badge to point to GitHub actions

---

docs/source/conf.py

When running `make html` the documentation fails to build with:
```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v3.5.3
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/james/code/github.com/django-activity-stream/.venv/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
execfile_(filename, namespace)
File "/home/james/code/github.com/django-activity-stream/.venv/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
exec(code, _globals)
File "/home/james/code/github.com/django-activity-stream/docs/source/conf.py", line 24, in <module>
django.setup()
File "/home/james/code/github.com/django-activity-stream/.venv/lib/python3.8/site-packages/ …
```

Fix documentation generation

---

actstream/__init__.py

**What does this PR do ?**
It solves the fix warnings default_app_config.
Full error details :
`RemovedInDjango41Warning: 'actstream' defines default_app_config = 'actstream.apps.ActstreamConfig'. Django now detects this configuration automatically. You can remove default_app_config.`

Fix django app config default warning

---

actstream/jsonfield.py

The django-mysql JSONField option (introduced before Django had its own builtin JSONField) has been removed, so we should not mention it in the docstring anymore.

Remove mysql details from docstring

---

actstream/actions.py
docs/concepts.rst

There are small typos in:
- actstream/actions.py
- docs/concepts.rst
Fixes:
- Should read `untranslated` rather than `unstranslated`.
- Should read `terminology` rather than `terminiology`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

actstream/registry.py

Easy fix, Django has removed the installed property, but they check if app_config is not None. Took over that check.

Fixes #515 - Make it work with Django 4.1

---

docs/installation.rst

typo correction in installation docs from 
django.contib.sites  to django.contrib.sites

fix typo in installation docs.

---

actstream/apps.py
actstream/follows.py
actstream/tests/test_activity.py

Fix #521: delete object-orphaned Follows
